<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Bert's Blog</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/4.0.0/github-markdown.min.css" integrity="sha512-Oy18vBnbSJkXTndr2n6lDMO5NN31UljR8e/ICzVPrGpSud4Gkckb8yUpqhKuUNoE+o9gAb4O/rAxxw1ojyUVzg==" crossorigin="anonymous" />
	<link rel="stylesheet/less" type="text/css" href="/blog/style.less" />
	<script src="//cdn.jsdelivr.net/npm/less@3.13" ></script>
	<style>
		.markdown-body {
			box-sizing: border-box;
			min-width: 200px;
			max-width: 980px;
			margin: 0 auto;
			padding: 45px;
		}
	
		@media (max-width: 767px) {
			.markdown-body {
				padding: 15px;
			}
		}
	</style>
</head>

<body>
	<div><div><article class="markdown-body"><h1 id="promise">Promise</h1>
<p><code>Promise</code> is a powerful alternative way to replace callback in JS. Compared to callback, <code>Promise</code> provides a better way to write coherent codes.</p>
<h2 id="how-to-use">How to use</h2>
<p>First of all, let&#39;s see its definition:</p>
<pre><code class="language-ts">/**
 * Represents the completion of an asynchronous operation
 */
interface Promise&lt;T&gt; {
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then&lt;TResult1 = T, TResult2 = never&gt;(onfulfilled?: ((value: T) =&gt; TResult1 | PromiseLike&lt;TResult1&gt;) | undefined | null, onrejected?: ((reason: any) =&gt; TResult2 | PromiseLike&lt;TResult2&gt;) | undefined | null): Promise&lt;TResult1 | TResult2&gt;;

    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch&lt;TResult = never&gt;(onrejected?: ((reason: any) =&gt; TResult | PromiseLike&lt;TResult&gt;) | undefined | null): Promise&lt;T | TResult&gt;;
}
</code></pre>
<p>The first function in then is resolve function, the second function is reject function which can on catch the error from <code>reject</code>, not from <code>throw</code>.</p>
<p>The functions <code>resolve</code> and <code>reject</code> is to change the status of <code>Promise</code>.</p>
<p>There is a demo:</p>
<pre><code class="language-ts">const resolveTask = () =&gt; new Promise((resolve, reject) =&gt; resolve(1))
.then(res =&gt; {
    console.log(&#39;resolve&#39;, res);
    throw Error(&#39;throw error&#39;)
}, err =&gt; {
    console.log(&#39;reject&#39;, err);
})
.catch(err =&gt; console.log(&#39;catch&#39;, err));

const rejectTask = () =&gt; new Promise((resolve, reject) =&gt; reject(1))
.then(res =&gt; {
    console.log(&#39;resolve&#39;, res);
    throw Error(&#39;throw error&#39;)
}, err =&gt; {
    console.log(&#39;reject&#39;, err);
})
.catch(err =&gt; console.log(&#39;catch&#39;, err));

// resolve 1
// catch Error: throw error
resolveTask();
// reject 1
rejectTask();
</code></pre>
<h2 id="promise-implementation">Promise implementation</h2>
<p>For me, the key point to understand Promise&#39;s then and catch is the event-loop. Because the main thread task will be operated to the end first. So the <code>thenList</code> and <code>onCatch</code> must be ready when the first callback starts.</p>
<p>There is a simple example I wrote:</p>
<pre><code class="language-ts">class MyPromise&lt;T&gt;{

    static statusList = {
        pending:Symbol(&#39;pending&#39;),
        resolved:Symbol(&#39;resolved&#39;),
        rejected:Symbol(&#39;rejected&#39;)
    } as const;

    private status = MyPromise.statusList.pending;
    private value: T = undefined;      // the container for transferring return value
    private thenList: Function[] = [];          //the container saving the callback in then
    private onCatch: Function | undefined = undefined;    //the container saving the catch function

    constructor(action: (resolve: Function, reject?: Function) =&gt; void) {
        // start filling thenList and onCatch
        action(this.resolve.bind(this), this.reject?.bind?.(this));
    }

    then(cb) {
        this.thenList.push(cb);
        return this;
    }

    catch(cb) {
        this.onCatch = cb;
        return this;
    }

    resolve(value) {
        this.status = MyPromise.statusList.resolved;
        this.value = value;
        for (let i=0;i&lt;this.thenList.length;i++){
            this.status = MyPromise.statusList.pending;
            try{
                this.value = this.thenList[i](this.value);
                this.status = MyPromise.statusList.resolved;
                if (this.value instanceof MyPromise) {
                    //if it&#39;s new Promise, change the target Promise
                    this.value.thenList = this.thenList.splice(i+1);
                    break;
                }
            } catch (e) {
                if (this.onCatch){
                    this.onCatch(e);
                    this.status = MyPromise.statusList.rejected;
                } else {
                    throw new Error(e.toString());
                }
            }
        }
    }

    reject(value) {
        this.status = MyPromise.statusList.rejected;
        this.value = value;
        if (this.onCatch){
            this.onCatch(this.value);
        } else {
            throw new Error(this.value.toString());
        }
    }
};

new MyPromise((resolve, reject) =&gt; {
    require(&#39;request&#39;)(&quot;http://www.npmjs.com&quot;, (err, res, body)=&gt;{
        if (!err &amp;&amp; res.statusCode === 200){
            resolve(res.statusCode);
        } else {
            reject(err);
        }
    })
}).then(data=&gt;{
    console.log(data);
    return 1;
})
    .then(data=&gt;{
        console.log(data);
    })
    .catch(err=&gt;{
    console.log(err);
});
</code></pre>
<h2 id="promiseall-promiserace-promisefinally-and-promiseparallel"><code>Promise.all</code>, <code>Promise.race</code>, <code>Promise.finally</code> and <code>Promise.parallel</code></h2>
<p>About <code>all</code> and <code>race</code>, I know a really vivid and interesting metaphor: The <code>all</code> is a horse race that ends when all horses reach the terminal point, the <code>race</code> is a horse race that ends when the first horse reaches the terminal point.</p>
<p>In other word, the <code>all</code> will return results of all callback tasks, the <code>race</code> will return the callback result of the first finished task.</p>
<p>Notice, <code>race</code> and <code>all</code> both will run the whole asynchronize task, the only different is the final returned value.</p>
<p>Their implements are as below:</p>
<pre><code class="language-ts">Promise.myRace = (tasks: Promise&lt;unknown&gt;[]) =&gt; new Promise((resolve, reject) =&gt; {
    tasks.forEach(async task =&gt; {
        try {
            const res = await task;
            // a Promise can be resolved once
            resolve(res);
        } catch (e) {
            reject(e);
        }
    });
});


Promise.myAll = (tasks: Promise&lt;unknown&gt;[]) =&gt; new Promise((resolve, reject) =&gt; {
    const res = [];
    tasks.forEach(async task =&gt; {
        try {
            const data = await task;
            res.push(data);
            if (res.length === tasks.length) resolve(res);
        } catch (e) {
            reject(e);
        }
    });
});

Promise.prototype.myFinally = function(cb) {
    return this.then(
        v =&gt; Promise.resolve(cb()).then(() =&gt; v),
        e =&gt; Promise.resolve(cb()).then(() =&gt; { throw e })
    )
};

Promise.parallelByReduce = (tasks: Promise&lt;unknown&gt;[]) =&gt; new Promise((resolve, reject) =&gt; {
    try {
        resolve(await tasks.reduce(async (acc, crr) =&gt; {
            acc = await acc;
            acc.push(await crr);
            return acc;
        }, []));
    } catch (e) {
        reject(e);
    }
});

Promise.parallelByRecursion = (tasks: Promise&lt;unknown&gt;[]) =&gt; new Promise((resolve, reject) =&gt; {
    const res = [];
    const iter = async () =&gt; {
        if (tasks.length &gt; 0) {
            const task = tasks.shift();
            const data = await task;
            res.push(data);
            iter();
        }
    };
    try {
        await iter();
        resolve(res);
    } catch (e) {
        reject(e);
    }
});
</code></pre>
<h2 id="async--await">async &amp; await</h2>
<p><code>async</code> and <code>await</code> it a better solution to replace <code>then</code>. Writing asynchronize codes with synchronize sequence.</p>
<h3 id="what-is-async-function">What is async function</h3>
<p>Actually, <code>async function</code> will return an <code>AsyncFunction</code> object, which can be created as below (notice: it is not a global variable):</p>
<pre><code class="language-ts">Object.getPrototypeOf(async function(){}).constructor
</code></pre>
<h3 id="always-return-promise">always return Promise</h3>
<p>It will always return a Promise object, even if we return other things:</p>
<pre><code class="language-ts">async function task() {
    return 1;
}
console.log(task())     // Promise { 1 }
</code></pre>
<h3 id="await-can-only-get-promiseresolve">await can only get Promise.resolve</h3>
<p>The <code>await</code> operator is used to wait for a <code>Promise</code>. It can only be used inside an <code>async function</code>. But it can only receive <code>Promise.resolve</code>. For example:</p>
<p>If the <code>Promise</code> is rejected, the await expression throws the rejected value.</p>
<pre><code class="language-ts">(async function () {
    const result = await Promise.resolve(&#39;success&#39;);
    console.log(result);
})();   // success

(async function () {
    const result = await Promise.reject(&#39;success&#39;);
    console.log(result);
})()    // UnhandledPromiseRejectionWarning: success
</code></pre>
<h2 id="conclusion">Conclusion</h2>
<p>In this way, for me, when I don&#39;t care about the error, I perfer to use <code>throw Error</code>, when I want to process
error, <code>Promise.reject</code> maybe more useful.</p>
</article></div></div>
</body>

</html>